### ISSUE TITLE
Remove Tier related code and docs

### ISSUE THREAD

**Issue by hayco** [knaw-huc/broccoli#46]
It appears we (no longer) use the Tier related code and it is burdening, amongst others, the config files and the indexing code. Double check we really don't use this anymore in TAV, then cleanup.

**Comment by svandaalen** [comment]
These are the only Broccoli endpoints I currently use in TAV:

- `${config.broccoliUrl}/projects/${config.id}/${bodyId}?overlapTypes=${overlapTypes}&includeResults=${includeResults}&views=${views}&relativeTo=${relativeTo}`
- `${broccoliUrl}/projects/${projectId}` (select distinct)
- `${projectConfig.broccoliUrl}/projects/${projectConfig.id}/search?${urlSearchParams}`
- `${projectConfig.broccoliUrl}/brinta/${projectConfig.id}/indices`

In the code of TAV I can't find any references to "Tiers".

**Comment by hayco** [comment]
Let's test this Tue Apr 30. Docker image and new `config.yml` are all set up on TT vm.
